// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ-7iQAWLqrl7bf-f9No13pXWSFtwsTjk',
    appId: '1:197391752441:web:561e07587d06d4e295d628',
    messagingSenderId: '197391752441',
    projectId: 'jwellery-shop-app',
    authDomain: 'jwellery-shop-app.firebaseapp.com',
    storageBucket: 'jwellery-shop-app.firebasestorage.app',
    measurementId: 'G-QNDLLX7PHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2Jxw8FuO7rW_xMUCg0SZ0SV1kCZX4nE',
    appId: '1:197391752441:android:b34b38af86029df995d628',
    messagingSenderId: '197391752441',
    projectId: 'jwellery-shop-app',
    storageBucket: 'jwellery-shop-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PchJ7AkwVQVlR5W5Mi70pRNZdhc0chQ',
    appId: '1:197391752441:ios:ece682a620322e5795d628',
    messagingSenderId: '197391752441',
    projectId: 'jwellery-shop-app',
    storageBucket: 'jwellery-shop-app.firebasestorage.app',
    iosClientId: '197391752441-s55ankmv4bser0p5dm6t2l4digasve69.apps.googleusercontent.com',
    iosBundleId: 'com.example.jwelleryBilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7PchJ7AkwVQVlR5W5Mi70pRNZdhc0chQ',
    appId: '1:197391752441:ios:ece682a620322e5795d628',
    messagingSenderId: '197391752441',
    projectId: 'jwellery-shop-app',
    storageBucket: 'jwellery-shop-app.firebasestorage.app',
    iosClientId: '197391752441-s55ankmv4bser0p5dm6t2l4digasve69.apps.googleusercontent.com',
    iosBundleId: 'com.example.jwelleryBilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ-7iQAWLqrl7bf-f9No13pXWSFtwsTjk',
    appId: '1:197391752441:web:eeaaf650fdf6958595d628',
    messagingSenderId: '197391752441',
    projectId: 'jwellery-shop-app',
    authDomain: 'jwellery-shop-app.firebaseapp.com',
    storageBucket: 'jwellery-shop-app.firebasestorage.app',
    measurementId: 'G-2T3D60YC7T',
  );
}
